name: BuildTasks

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main, task0, task1, task2, task3, task4, task5, task6, task7, task10, task11, task12 ]

env:
  BUILD_TYPE: Debug

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2

    - name: get_glfw
      run: |
        git submodule update --init -- 3rd_party/glfw
        cd 3rd_party/glfw
        cmake .
        cmake --build .

    - name: get_delfem2
      run: |
        git submodule update --init -- 3rd_party/delfem2

    - name: build
      run: |
        cmake .
        cmake --build .
